name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  # Checkout项目
      uses: actions/checkout@master
    - name: Set up Node.js  # Nodejs版本
      uses: actions/setup-node@master
      with:
        node-version: 12.13.0
    - name: Deploy to GitHub Pages
      uses: jimyuan/color-lab@master
      env:
        BUILD_SCRIPT: npm install && npm run build
        EMAIL: jimyuan@gmail.com          # 你的Github邮箱
        GH_TOKEN: ${{ secrets.COLORLAB }} # 看下文描述
        BUILD_DIR: docs/